// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKa8kkTFxQ4oj55cXgar4n5dHYMz8NsIs',
    appId: '1:803035657155:web:4517750540c8ea862b8376',
    messagingSenderId: '803035657155',
    projectId: 'imdb-1bdbd',
    authDomain: 'imdb-1bdbd.firebaseapp.com',
    storageBucket: 'imdb-1bdbd.appspot.com',
    measurementId: 'G-J8LMW3WQ3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw3fjl0J0PyNLTSmagL4Uys7HHwwD4SPA',
    appId: '1:803035657155:android:663e26c7e3b603072b8376',
    messagingSenderId: '803035657155',
    projectId: 'imdb-1bdbd',
    storageBucket: 'imdb-1bdbd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0zQzLYEl9xx78iPaiMRsxnT4wIyY1x5w',
    appId: '1:803035657155:ios:70052797057c54e72b8376',
    messagingSenderId: '803035657155',
    projectId: 'imdb-1bdbd',
    storageBucket: 'imdb-1bdbd.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0zQzLYEl9xx78iPaiMRsxnT4wIyY1x5w',
    appId: '1:803035657155:ios:03f1d20e9ee3f6f62b8376',
    messagingSenderId: '803035657155',
    projectId: 'imdb-1bdbd',
    storageBucket: 'imdb-1bdbd.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
